version: "3.1"
services:
  spring-boot-docker:
    image: lfallo1/thymeleafdemo:9b059a5
    restart: always
    ports:
      - "8082:8082"
    links:
      - postgres:postgres
    depends_on:
      - postgres
    environment:
      JASYPT_PASSWORD: prod_secret123
      SPRING_PROFILES_ACTIVE: prod
  postgres:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: production_secret
      POSTGRES_DB: SpringProducts
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
